AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Itslearning Scraper Lambda Function

Globals:
  Function:
    Timeout: 300
    MemorySize: 2048

Resources:
  ItslearningScraper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_package/function.zip
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
      Environment:
        Variables:
          PARAMETER_PREFIX: /itslearning_scraper
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:764866452798:layer:chrome-selenium:48

Outputs:
  ItslearningScraperFunction:
    Description: "Itslearning Scraper Lambda Function ARN"
    Value: !GetAtt ItslearningScraper.Arn